# Build settings
markdown: kramdown
# Site settings
title: Hardened GNU/Linux
logo: hardenedlinux.gif
email: hardenedlinux@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  We are a group of free software enthusiasts, anarchists, cyber security researchers. 0ld sch00l long lives!!!

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.hardenedlinux.org" # the base hostname & protocol for your site
twitter_username: hardenedlinux
github_username:  hardenedlinux

# Build settings
markdown: kramdown
